---
- hosts: ansible-host
  tasks:
    - name: Create a folder using shell module
      shell: "mkdir ~/shellmodule"
    - name: Create folder using file module
      file:
        state: directory
        path: "~/filemodule-pjjb"