---
- hosts: ansible-host
  tasks:
    #forced idempotency
    - name: Check if shellmodule-pjjb already exists
      stat:
        path: "~/shellmodule-pjjb"
      register: shellmodulevariable

    - debug: var=shellmodulevariable

    - name: Create a folder using shell module
      shell: "mkdir ~/shellmodule-pjjb"
      when: shellmodulevariable.stat.exists != true

    - name: Create folder using file module
      file:
        state: directory
        path: "~/filemodule-pjjb"