---
- hosts: ansible-host
  tasks:
    #forced idempotency
    - name: Check if shellmodule-pjjb already exists
      stat:
        path: "~/shellmodule-pjjb" 
    - name: Create a folder using shell module
      shell: "mkdir ~/shellmodule-pjjb"
    - name: Create folder using file module
      file:
        state: directory
        path: "~/filemodule-pjjb"