#forced idempotency
- name: Check if {{ shellfoldername }} already exists
  stat:
    path: "~/{{ shellfoldername }}"
  register: shellmodulevariable

- debug: var=shellmodulevariable

- name: Create a folder using shell module
  shell: "mkdir ~/{{ shellfoldername }}"
  when: shellmodulevariable.stat.exists != true

- name: Create folder using file module
  file:
    state: directory
    path: "~/{{ filefoldername }}"